server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:6434/impulse_db
    username: postgres
    password: postgres

jwt:
  secret: secret-key
  lifetime: 60m

api:
  uri: /api/v1
  cors:
    allowed-origins: http://localhost:8080,http://localhost:5173,http://localhost:5174
      
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true